name: Release with SBOM and Signatures

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-sign:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Install Syft for SBOM
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /tmp
        sudo mv /tmp/syft /usr/local/bin
    
    - name: Install Cosign
      uses: sigstore/cosign-installer@v3
    
    - name: Log into registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build release
      run: |
        cargo build --release --all-features
        cargo test --release
    
    - name: Generate SBOM
      run: |
        syft dir:. -o cyclonedx-json > sbom.cyclonedx.json
        syft dir:. -o spdx-json > sbom.spdx.json
        syft dir:. -o table > sbom.txt
    
    - name: Build container
      run: |
        docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }} .
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
    
    - name: Sign container and SBOM
      run: |
        # Sign the container
        cosign sign --yes ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
        
        # Attach SBOM to container
        cosign attach sbom --sbom sbom.cyclonedx.json \
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
        
        # Sign the SBOM
        cosign sign --yes --attachment sbom \
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
    
    - name: Generate SLSA Provenance
      uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v1.10.0
      with:
        image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        digest: ${{ steps.build.outputs.digest }}
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: security-artifacts
        path: |
          sbom.*.json
          sbom.txt
